export type UserType ={
    id?:string; // Optional if the ID is generated by the backend
    userId:string;
    name: string;
    email: string;
    password: string;
    contact: string;
    gender: string;
    role:string;
    address: {
    addressline: string;
    city: string;
    state: string;
    pincode: string;
    country: string;};
    bids:{
            bidId:string,
            auctionId:string,
            bidAmount:number,
            time:string,
            status:string
         }[]; 
    payments: {
            paymentid:string,
            paymentdate:string,
            auctionId:string,
            amount:number,
            status:string
         }[];
    reviews: {
            reviewid:string,
            targetuserid:string,
            rating:number,
            comment:string,
            date:string
         }[];
}

